import type { Project } from './types';

export const INITIAL_PROJECTS: Project[] = [
  {
    id: 'proj-calf20',
    code: '1501-CALF20',
    name: 'TÜBİTAK 1501',
    subtitle: 'CALF-20 HSM Scale-up',
    color: 'bg-red-500',
    startDate: '15 Oca',
    endDate: '31 Ara',
    daysLeft: 621,
    leaderId: 'u1',
    memberIds: ['u1', 'u3', 'u4'],
    budgetK: 2400,
    spentK: 320,
    status: 'aktif',
    workPackages: [
      {
        id: 'IP1',
        title: 'Literatür taraması ve spec belirleme',
        status: 'tamam',
        deadline: '15 Mar',
        notes: 'Tüm literatür tarandı, spec dokümanı yazıldı ve onaylandı. 45 makale, 3 patent incelendi.',
      },
      {
        id: 'IP2',
        title: 'HSM parametre optimizasyonu (1-2L)',
        status: 'devam',
        deadline: '30 Haz',
        notes: "1L reaktörde 6 farklı RPM × 3 sıcaklık kombinasyonu denendi. 13000 RPM'de overheating sorunu var — soğutma çeket eklenecek. 12 kombinasyon kaldı.",
      },
      {
        id: 'IP3',
        title: 'Pilot scale-up (10kg batch)',
        status: 'bekliyor',
        deadline: '1 Ara',
        notes: '',
      },
      {
        id: 'IP4',
        title: 'Karakterizasyon & kalite doğrulama',
        status: 'bekliyor',
        deadline: '31 Mar',
        notes: '',
      },
      {
        id: 'IP5',
        title: 'Ara rapor + final rapor',
        status: 'bekliyor',
        deadline: '30 Kas',
        notes: '',
      },
    ],
    reportPeriods: [
      { id: 'R1', title: '1. Ara Rapor', date: '15 Tem', daysLeft: 87, status: 'bekliyor' },
      { id: 'R2', title: '2. Ara Rapor', date: '15 Oca', daysLeft: 271, status: 'bekliyor' },
      { id: 'R3', title: '3. Ara Rapor', date: '15 Tem', daysLeft: 452, status: 'bekliyor' },
      { id: 'R4', title: 'Sonuç Raporu', date: '31 Oca', daysLeft: 652, status: 'bekliyor' },
    ],
    notes: 'CALF-20 = Zn-oksalat-triazolat. TRL 4→6-7. Malzeme (advanced materials) kapsamında — CO₂ uygulaması vurgulanmıyor.',
  },
  {
    id: 'proj-solx22',
    code: '1507-SOLX22',
    name: 'TÜBİTAK 1507',
    subtitle: 'SOLX-22 Güneş İzleme',
    color: 'bg-amber-500',
    startDate: '01 Mar',
    endDate: '28 Eyl',
    daysLeft: 145,
    leaderId: 'u3',
    memberIds: ['u3', 'u6'],
    budgetK: 800,
    spentK: 210,
    status: 'aktif',
    workPackages: [
      {
        id: 'WP1',
        title: 'Sistem tasarımı ve simülasyon',
        status: 'tamam',
        deadline: '30 Eyl',
        notes: 'MATLAB/Simulink modeli tamamlandı, doğrulama raporu hazır.',
      },
      {
        id: 'WP2',
        title: 'Prototip geliştirme',
        status: 'devam',
        deadline: '30 Haz',
        notes: 'PCB tasarımı revize aşamasında. Üretim Temmuz başı hedefleniyor.',
      },
      {
        id: 'WP3',
        title: 'Saha validasyonu',
        status: 'bekliyor',
        deadline: '28 Eyl',
        notes: '',
      },
      {
        id: 'WP4',
        title: 'Raporlama ve yayın',
        status: 'bekliyor',
        deadline: '28 Eyl',
        notes: '',
      },
    ],
    reportPeriods: [
      { id: 'R1', title: '1. Ara Rapor', date: '31 Mar', daysLeft: 0, status: 'tamam' },
      { id: 'R2', title: '2. Ara Rapor', date: '30 Haz', daysLeft: 68, status: 'devam' },
      { id: 'R3', title: '3. Ara Rapor', date: '15 Ağu', daysLeft: 114, status: 'bekliyor' },
      { id: 'R4', title: 'Sonuç Raporu', date: '28 Eyl', daysLeft: 145, status: 'bekliyor' },
    ],
    notes: 'SOL-X22: Güneş izleme sistemi için düşük güçlü kontrol elektroniği geliştirme projesi.',
  },
  {
    id: 'proj-dacota',
    code: 'DACOTA-EU24',
    name: 'DACOTA',
    subtitle: 'Veri Entegrasyon Platformu',
    color: 'bg-blue-500',
    startDate: '01 Haz',
    endDate: '31 Mar',
    daysLeft: 312,
    leaderId: 'u4',
    memberIds: ['u4', 'u1', 'u7'],
    budgetK: 1800,
    spentK: 540,
    status: 'aktif',
    workPackages: [
      {
        id: 'WP1',
        title: 'Konsorsiyum koordinasyonu',
        status: 'tamam',
        deadline: '30 Kas',
        notes: "Kick-off toplantısı Brüksel'de gerçekleştirildi. Tüm ortaklar görev dağılımını imzaladı.",
      },
      {
        id: 'WP2',
        title: 'Veri entegrasyon altyapısı',
        status: 'tamam',
        deadline: '31 Mar',
        notes: 'API gateway ve veri modelleme tamamlandı. Testler geçti.',
      },
      {
        id: 'WP3',
        title: 'Pilot uygulama',
        status: 'devam',
        deadline: '30 Eyl',
        notes: 'İspanya ve Türkiye pilot alanları aktif. Veri akışı stabil.',
      },
    ],
    reportPeriods: [
      { id: 'R1', title: 'M6 Raporu', date: '30 Kas', daysLeft: 0, status: 'tamam' },
      { id: 'R2', title: 'M12 Raporu', date: '31 May', daysLeft: 0, status: 'tamam' },
      { id: 'R3', title: 'M24 Raporu', date: '31 May', daysLeft: 38, status: 'devam' },
    ],
    notes: 'Horizon Europe çerçevesinde 6 ülke 11 ortak. Türk koordinatör: Helios.',
  },
  {
    id: 'proj-sundrop',
    code: 'SUNDROP-25',
    name: 'SUNDROP',
    subtitle: 'Ar-Ge Projesi 2025',
    color: 'bg-emerald-500',
    startDate: '01 Oca',
    endDate: '31 Ara',
    daysLeft: 521,
    leaderId: 'u6',
    memberIds: ['u6', 'u3'],
    budgetK: 600,
    spentK: 0,
    status: 'aktif',
    workPackages: [
      {
        id: 'WP1',
        title: 'Fizibilite ve ihtiyaç analizi',
        status: 'bekliyor',
        deadline: '30 Haz',
        notes: '',
      },
      {
        id: 'WP2',
        title: 'Ar-Ge ve prototipleme',
        status: 'bekliyor',
        deadline: '31 Ara',
        notes: '',
      },
      {
        id: 'WP3',
        title: 'Sonuç ve raporlama',
        status: 'bekliyor',
        deadline: '31 Ara',
        notes: '',
      },
    ],
    reportPeriods: [
      { id: 'R1', title: '1. Ara Rapor', date: '30 Haz', daysLeft: 68, status: 'bekliyor' },
      { id: 'R2', title: '2. Ara Rapor', date: '30 Eyl', daysLeft: 160, status: 'bekliyor' },
      { id: 'R3', title: 'Sonuç Raporu', date: '31 Ara', daysLeft: 521, status: 'bekliyor' },
    ],
    notes: '',
  },
];
