import type { PurchaseAuthor, PurchaseRequest } from './types';

const ASSIGNEE_GIZEM: PurchaseAuthor = {
  id: 'u1',
  name: 'Gizem Uysal',
  initials: 'GU',
  color: 'bg-indigo-100 text-indigo-700',
};

export const INITIAL_PURCHASES: PurchaseRequest[] = [
  {
    id: 'pr-seed-001',
    type: 'ariza',
    title: 'Santrifüj kapak kilidi',
    description: "Lab checklist'te tespit edildi, parça siparişi gerekli",
    urgency: 'acil',
    quantity: '1 adet',
    status: 'yeni',
    createdAt: '2026-04-16T09:00:00.000Z',
    createdBy: { id: 'u4', name: 'Melike Gürkan', initials: 'MG', color: 'bg-pink-100 text-pink-700' },
    assignedTo: ASSIGNEE_GIZEM,
    details: {
      kind: 'ariza',
      device: 'Santrifüj',
      detectedAt: '2026-04-15',
      faultType: 'Kapak kilit mekanizması',
    },
  },
  {
    id: 'pr-seed-002',
    type: 'hizmet',
    title: 'BET analizi — 5 numune',
    description: 'DACOTA projesi için CALF-20 partilerinin yüzey alanı ölçümü',
    urgency: 'normal',
    quantity: '5 numune',
    estimatedPrice: '8.500 TL',
    status: 'siparis-verildi',
    createdAt: '2026-04-14T11:30:00.000Z',
    createdBy: { id: 'u2', name: 'Gizem Şanyılmaz', initials: 'GŞ', color: 'bg-purple-100 text-purple-700' },
    assignedTo: ASSIGNEE_GIZEM,
    attachment: {
      name: 'boun_fatura_nisan.pdf',
      size: 184_320,
      type: 'application/pdf',
      dataUrl: 'data:application/pdf;base64,',
    },
    details: {
      kind: 'hizmet',
      serviceType: 'Analiz / karakterizasyon',
      company: 'BOUN SEM-TEM Lab',
      invoiceNo: 'FT-2026-0451',
      invoiceDate: '2026-04-10',
    },
  },
  {
    id: 'pr-seed-003',
    type: 'kimyasal',
    title: '1,2,4-Triazol 100 g',
    description: 'CALF-20 sentezi için linker stoğu yenilemesi',
    urgency: 'normal',
    quantity: '100 g',
    estimatedPrice: '2.400 TL',
    link: 'https://www.sigmaaldrich.com/',
    status: 'geldi',
    createdAt: '2026-04-08T08:15:00.000Z',
    createdBy: { id: 'u3', name: 'İlker Deveci', initials: 'İD', color: 'bg-emerald-100 text-emerald-700' },
    assignedTo: ASSIGNEE_GIZEM,
    details: {
      kind: 'kimyasal',
      cas: '288-88-0',
      purity: '≥99%',
      manufacturer: 'Sigma T54406',
      storage: 'oda',
    },
  },
  {
    id: 'pr-seed-004',
    type: 'sarf',
    title: 'Nitril eldiven (M, 10 kutu)',
    description: 'Stok tükendi — yanlış beden gönderildi, iade ediliyor',
    urgency: 'yuksek',
    quantity: '10 kutu',
    estimatedPrice: '1.800 TL',
    status: 'iptal-iade',
    createdAt: '2026-04-05T14:00:00.000Z',
    createdBy: { id: 'u7', name: 'İrem Rabia', initials: 'İR', color: 'bg-teal-100 text-teal-700' },
    assignedTo: ASSIGNEE_GIZEM,
    details: {
      kind: 'sarf',
      brandModel: 'Beybi NitriMax',
      supplier: 'LabSarf A.Ş.',
    },
  },
];
